# Generated by Django 4.1.5 on 2023-01-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_extracted',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamelist.game'),
        ),
        migrations.AlterField(
            model_name='genre_extracted',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamelist.genre'),
        ),
    ]
